-- AlterTable
ALTER TABLE "directeur_signatures" ADD COLUMN     "qrCodePositionX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "qrCodePositionY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "qrCodeSize" DOUBLE PRECISION NOT NULL DEFAULT 80,
ADD COLUMN     "signatureHeight" DOUBLE PRECISION NOT NULL DEFAULT 60,
ADD COLUMN     "signatureWidth" DOUBLE PRECISION NOT NULL DEFAULT 150;
